language: rust
sudo: false
env: RUST_BACKTRACE=1

cache:
    directories:
    - $HOME/.cargo
    - $HOME/.cache/sccache

before_script:
  - docker pull marwes/try_gluon_builder || true
  - docker pull marwes/try_gluon || true

script:
  - ./scripts/travis.sh

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script:
    - docker push marwes/try_gluon_builder
    - docker push marwes/try_gluon
  on:
    branch: master
