language: rust
sudo: false
services:
  - docker
env: RUST_BACKTRACE=1

addons:
  apt:
    packages:
      - docker-ce

before_script:
  - docker pull marwes/try_gluon:builder || true
  - docker pull marwes/try_gluon || true

script:
  - ./scripts/travis.sh

after_script:
  - docker images

before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin

deploy:
  provider: script
  script:
    - docker push marwes/try_gluon:builder
    - docker push marwes/try_gluon
  on:
    branch: master
