[package]
name = "lambda"
version = "0.1.0"
authors = ["Markus Westerlind <marwes91@gmail.com>"]

[lib]
name = "lambda"
crate-type = ["dylib"]

[dependencies]
try_gluon = { path = ".." }

crowbar = "0.1"
cpython = { version = "*", default-features = false, features = ["python27-sys"] }
